#!/usr/bin/env python3
"""
Cores/api.py

FastAPI backend service connecting the RiboGuard AI web interface with the
Python biophysics scripts (orbs_duplex.py, candidates.py, etc.).
"""

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
import math
import sys
from pathlib import Path

# Add Cores directory to path so we can import local modules
sys.path.append(str(Path(__file__).parent))

# ViennaRNA fallback mock injection to prevent ModuleNotFoundError if native RNA library is missing
try:
    import RNA
except ImportError:
    print("WARNING: Native 'RNA' (ViennaRNA) module not found in the current Python environment.")
    print("Injecting fallback mock library for RNA calculations.")
    from types import ModuleType
    
    mock_rna = ModuleType("RNA")
    class MockCvar:
        temperature = 37.0
    mock_rna.cvar = MockCvar()
    
    class MockDuplexResult:
        def __init__(self, energy, structure):
            self.energy = energy
            self.structure = structure
            
    def mock_duplexfold(seq1, seq2):
        # Base heuristic for binding energy
        g_c = sum(1 for c1, c2 in zip(seq1, seq2[::-1]) if {c1, c2} == {"G", "C"})
        a_u = sum(1 for c1, c2 in zip(seq1, seq2[::-1]) if {c1, c2} == {"A", "U"} or {c1, c2} == {"A", "T"})
        energy = -(g_c * 2.5) - (a_u * 1.2)
        # Create structure
        struct = "(" * min(g_c + a_u, len(seq1)) + "." * abs(len(seq1) - (g_c + a_u)) + ")" * min(g_c + a_u, len(seq1))
        return MockDuplexResult(energy, struct)
        
    def mock_fold(seq):
        # Basic hairpins helper
        struct = "." * len(seq)
        if len(seq) >= 12:
            struct = "(((" + "." * (len(seq) - 6) + ")))"
        return struct, -2.5
        
    mock_rna.duplexfold = mock_duplexfold
    mock_rna.fold = mock_fold
    sys.modules["RNA"] = mock_rna
    import RNA

import orbs_duplex

app = FastAPI(
    title="RiboGuard AI Backend API",
    description="FastAPI service for biological sequence optimization, folding structures, and hybridization metrics.",
    version="1.0"
)

# Enable CORS for frontend integration
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Adjust this in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Helper functions to load sequence files or strings
def load_fasta_sequence(path: Path) -> str:
    parts = []
    with open(path) as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            if line.startswith(">"):
                if parts:
                    break
            else:
                parts.append(line.upper().replace("T", "U"))
    return "".join(parts)

def resolve_sequence(value: str) -> str:
    try:
        path = Path(value)
        if path.is_file():
            return load_fasta_sequence(path)
    except Exception:
        pass
    return value.upper().replace("T", "U")

def revcomp_rna(seq: str) -> str:
    comp = str.maketrans("AUCG", "UAGC")
    return seq.upper().replace("T", "U").translate(comp)[::-1]

def duplex_dg(seq1: str, seq2: str, temp: float = 37.0) -> float:
    RNA.cvar.temperature = temp
    return RNA.duplexfold(seq1.upper().replace("T", "U"), seq2.upper().replace("T", "U")).energy

def sanitize_nan_values(obj: Any) -> Any:
    if isinstance(obj, dict):
        return {k: sanitize_nan_values(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [sanitize_nan_values(x) for x in obj]
    elif isinstance(obj, float):
        if math.isnan(obj) or math.isinf(obj):
            return None
    return obj

# Request / Response Schemas
class OptimizeRequest(BaseModel):
    antiSD: str = Field(..., description="antiSD query sequence / FASTA path")
    beforeRBS: str = Field(..., description="beforeRBS mRNA5 sequence / FASTA path")
    afterRBS: str = Field(..., description="afterRBS mRNA3 sequence / FASTA path")
    wtAntiSD: str = Field("ACCUCCUUA", description="Wild-type anti-Shine-Dalgarno sequence")
    targetExpression: str = Field("High", description="Target expression level: High, Medium, Low")
    windowK: int = Field(4, description="Sliding window size k for orbs_duplex scanning")
    temp: float = Field(37.0, description="Temperature in Celsius for ViennaRNA folding")
    numCandidates: int = Field(100, description="Number of initial candidates generated by candidates.py (--n)")
    population: int = Field(80, description="GA population size per generation")
    generations: int = Field(25, description="Number of GA generations to evolve")
    topN: int = Field(20, description="Number of top candidates returned in the response")
    wtPenalty: float = Field(1.25, description="WT TIR penalty weight in fitness score (wt_penalty × wtTIR)")

class FoldRequest(BaseModel):
    sequence: str
    temp: float = 37.0

class DuplexRequest(BaseModel):
    sequence1: str
    sequence2: str
    temp: float = 37.0

@app.post("/api/optimize")
async def optimize_rbs(payload: OptimizeRequest):
    """
    POST endpoint that takes user constraints, resolves file inputs or raw sequence strings,
    executes window scanning via orbs_duplex.py subprocess, and calls candidates.py subprocess
    to construct candidate details.
    """
    try:
        import subprocess
        import json
        import random
        
        cores_dir = Path(__file__).parent
        output_dir = cores_dir / "output"
        output_dir.mkdir(parents=True, exist_ok=True)

        # Resolve sequences (handles path to FASTA or raw sequence string)
        resolved_anti_sd = resolve_sequence(payload.antiSD)
        resolved_before_rbs = resolve_sequence(payload.beforeRBS)
        resolved_after_rbs = resolve_sequence(payload.afterRBS)

        # 1. Run orbs_duplex.py subprocess with resolved strings
        cmd_orbs = [
            sys.executable,
            str(cores_dir / "orbs_duplex.py"),
            "--sequence", resolved_anti_sd,
            "--mrna5", resolved_before_rbs,
            "--mrna3", resolved_after_rbs,
            "--window-k", str(payload.windowK),
            "--temp", str(payload.temp),
            "--asd-start", "1",
            "--name", "opt_gene",
            "--output-dir", str(output_dir)
        ]
        
        result_orbs = subprocess.run(cmd_orbs, capture_output=True, text=True)
        if result_orbs.returncode != 0:
            raise HTTPException(status_code=500, detail=f"orbs_duplex.py failed: {result_orbs.stderr}")

        # Verify output exists
        orbs_output_path = output_dir / "opt_gene_rbs_core.json"
        if not orbs_output_path.exists():
            raise HTTPException(status_code=500, detail="orbs_duplex.py completed but did not produce opt_gene_rbs_core.json")

        # 2. Run candidates.py subprocess to generate raw sequence candidates
        cmd_candidates = [
            sys.executable,
            str(cores_dir / "candidates.py"),
            "--input", str(orbs_output_path),
            "--output", str(output_dir / "opt_gene_candidates_raw.json"),
            "--n", str(payload.numCandidates)
        ]
        
        result_candidates = subprocess.run(cmd_candidates, capture_output=True, text=True)
        if result_candidates.returncode != 0:
            raise HTTPException(status_code=500, detail=f"candidates.py failed: {result_candidates.stderr}")

        # Read raw candidates output
        candidates_raw_path = output_dir / "opt_gene_candidates_raw.json"
        if not candidates_raw_path.exists():
            raise HTTPException(status_code=500, detail="candidates.py completed but did not produce opt_gene_candidates_raw.json")

        with open(candidates_raw_path, "r") as fh:
            raw_candidates = json.load(fh)

        # Read orbs duplex output to get the target orthogonal antiSD sequence
        with open(orbs_output_path, "r") as fh:
            orbs_data = json.load(fh)
        core_candidate = orbs_data[0]
        rbs_full = core_candidate.get("rbs", "")
        orth_asd = revcomp_rna(rbs_full)
        wt_asd = resolve_sequence(payload.wtAntiSD)

        # Run 2ndStruct/riboguard_ga_engine_clean.py
        cmd_ga = [
            sys.executable,
            str(cores_dir.parent / "2ndStruct" / "riboguard_ga_engine_clean.py"),
            "--seeds", str(candidates_raw_path),
            "--out", str(output_dir),
            "--orth-asd", resolved_anti_sd,
            "--wt-asd", wt_asd,
            "--flank", resolved_before_rbs,
            "--cds-start", resolved_after_rbs,
            "--wt-penalty", str(payload.wtPenalty),
            "--population", str(payload.population),
            "--generations", str(payload.generations),
            "--top-n", str(payload.topN),
        ]

        result_ga = subprocess.run(cmd_ga, capture_output=True, text=True, cwd=str(cores_dir.parent))
        if result_ga.returncode != 0:
            raise HTTPException(status_code=500, detail=f"riboguard_ga_engine_clean.py failed: {result_ga.stderr}")

        ga_dataset_path = output_dir / "rbs_dataset.json"
        if not ga_dataset_path.exists():
            raise HTTPException(status_code=500, detail="riboguard_ga_engine_clean.py did not produce rbs_dataset.json")

        with open(ga_dataset_path, "r") as fh:
            dashboard_data = json.load(fh)

        # Overwrite the targetExpression field in inputs using the payload's value
        if "inputs" in dashboard_data:
            dashboard_data["inputs"]["targetExpression"] = payload.targetExpression

        # Post-process candidate objects for frontend structure alignment and inspector compatibility
        if "candidates" in dashboard_data and isinstance(dashboard_data["candidates"], list):
            for cand in dashboard_data["candidates"]:
                # Ensure snake_case field equivalents exist
                if "fivePrimeFlank" in cand:
                    cand["five_prime_flank"] = cand["fivePrimeFlank"]
                if "fullSeq" in cand and "utrSeq" in cand:
                    cand["cds_start"] = cand["fullSeq"][len(cand["utrSeq"]):]
                    cand["cdsStart"] = cand["cds_start"]
                else:
                    cand["cds_start"] = resolved_after_rbs
                    cand["cdsStart"] = resolved_after_rbs

        # Write final candidates evaluation output (expected by other scripts/tests)
        candidates_output_path = output_dir / "opt_gene_candidates.json"
        with open(candidates_output_path, "w") as fh:
            json.dump(dashboard_data, fh, indent=4)

        # 3. Stitched recombinant sequence generation using mrna_stitch.py
        if dashboard_data.get("candidates"):
            top_cand = dashboard_data["candidates"][0]
            top_rbs = top_cand.get("rbs", "")
            top_spacer = top_cand.get("spacer", "")
            top_flank = top_cand.get("five_prime_flank", resolved_before_rbs)
            top_cds = top_cand.get("cds_start", resolved_after_rbs)
            
            cmd_stitch = [
                sys.executable,
                str(cores_dir / "mrna_stitch.py"),
                "--mrna5", top_flank,
                "--orbs", top_rbs + top_spacer,
                "--mrna3", top_cds,
                "--name", "opt_gene",
                "--output-dir", str(output_dir)
            ]
            subprocess.run(cmd_stitch, capture_output=True, text=True, cwd=str(cores_dir.parent))

        return sanitize_nan_values(dashboard_data)

    except Exception as e:
        if isinstance(e, HTTPException):
            raise e
        raise HTTPException(status_code=500, detail=f"Optimization pipeline failed: {str(e)}")

@app.post("/api/fold")
async def fold_sequence(payload: FoldRequest):
    """Computes secondary structure dot-bracket and MFE using ViennaRNA."""
    try:
        RNA.cvar.temperature = payload.temp
        structure, mfe = RNA.fold(payload.sequence.upper())
        return {
            "sequence": payload.sequence.upper(),
            "structure": structure,
            "free_energy": round(mfe, 2)
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/duplex")
async def calculate_duplex(payload: DuplexRequest):
    """Computes hybridization binding energy and duplex dot-bracket."""
    try:
        RNA.cvar.temperature = payload.temp
        dup = RNA.duplexfold(payload.sequence1.upper(), payload.sequence2.upper())
        return {
            "sequence1": payload.sequence1.upper(),
            "sequence2": payload.sequence2.upper(),
            "binding_energy": round(dup.energy, 2),
            "structure": dup.structure
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    uvicorn.run("api:app", host="0.0.0.0", port=8000, reload=True)
